[package]
name = "rust-amqp-to-mysql-consumer"
version = "0.1.0"
authors = ["Wojciech Guła <gulasz101@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
