version: "3.2"

volumes:
  data_mysql:

services:
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
  mysql:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080